// SET CONTENT
export const SET_DCARD_DETAIL = "SET_DCARD_DETAIL";
export const SET_DCARDS_LIST = "SET_DCARDS_LIST";

// REQUEST PRODUCTS FROM DATABASE
export const BEGIN_DCARDS_REQUEST = "BEGIN_DCARDS_REQUEST";
export const SUCCESS_DCARDS_REQUEST = "SUCCESS_DCARDS_REQUEST";
export const FAIL_DCARDS_REQUEST = "FAIL_DCARDS_REQUEST";

// REQUEST LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
