// SET CONTENT
export const SET_DCARD_DETAIL = "SET_DCARD_DETAIL";
export const SET_DCARDS_LIST = "SET_DCARDS_LIST";
export const SET_MORE_DCARDS_LIST = "SET_MORE_DCARDS_LIST";
export const SET_SEARCH_DCARDS_LIST = "SET_SEARCH_DCARDS_LIST";
export const SET_MORE_SEARCH_DCARDS_LIST = "SET_MORE_SEARCH_DCARDS_LIST";

// REQUEST DCARDS FROM SERVER
export const BEGIN_DCARDS_REQUEST = "BEGIN_DCARDS_REQUEST";
export const SUCCESS_DCARDS_REQUEST = "SUCCESS_DCARDS_REQUEST";
export const FAIL_DCARDS_REQUEST = "FAIL_DCARDS_REQUEST";
export const BEGIN_MORE_DCARDS_REQUEST = "BEGIN_MORE_DCARDS_REQUEST";
export const SUCCESS_MORE_DCARDS_REQUEST = "SUCCESS_MORE_DCARDS_REQUEST";
export const FAIL_MORE_DCARDS_REQUEST = "FAIL_MORE_DCARDS_REQUEST";
export const BEGIN_DCARD_DETAIL_REQUEST = "BEGIN_DCARD_DETAIL_REQUEST";
export const SUCCESS_DCARD_DETAIL_REQUEST = "SUCCESS_DCARD_DETAIL_REQUEST";
export const FAIL_DCARD_DETAIL_REQUEST = "FAIL_DCARD_DETAIL_REQUEST";
export const BEGIN_SEARCH_DCARDS_REQUEST = "BEGIN_SEARCH_DCARDS_REQUEST";
export const SUCCESS_SEARCH_DCARDS_REQUEST = "SUCCESS_SEARCH_DCARDS_REQUEST";
export const FAIL_SEARCH_DCARDS_REQUEST = "FAIL_SEARCH_DCARDS_REQUEST";
export const BEGIN_MORE_SEARCH_DCARDS_REQUEST = "BEGIN_MORE_SEARCH_DCARDS_REQUEST";
export const SUCCESS_MORE_SEARCH_DCARDS_REQUEST = "SUCCESS_MORE_SEARCH_DCARDS_REQUEST";
export const FAIL_MORE_SEARCH_DCARDS_REQUEST = "FAIL_MORE_SEARCH_DCARDS_REQUEST";

// REQUEST LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

export const CLOSE_LOGIN_ALERT = "CLOSE_LOGIN_ALERT";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";

// EXPAND BOTTOM SHEET
export const EXPAND_BOTTOM_SHEET = "EXPAND_BOTTOM_SHEET";
export const UNEXPAND_BOTTOM_SHEET = "UNEXPAND_BOTTOM_SHEET";
